controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: /
    controller: App\Controller\SecurityController::login

account:
    path: /creer-un-compte
    controller: App\Controller\AccountController::index

candidate_dashboard:
    path: /candidat/tableau-de-bord
    controller: App\Controller\CandidateDashboardController::index

candidate_profile:
    path: /candidat/mon-profil
    controller: App\Controller\CandidateProfileController::index

candidate_jobpostings:
    path: /candidat/annonces
    controller: App\Controller\CandidateJobPostingsController::index

candidate_jobpostings_details:
    path: /candidat/annonces/{title}
    controller: App\Controller\CandidateJobPostingsController::index

recruiter_dashboard:
    path: /recruteur/tableau-de-bord
    controller: App\Controller\RecruiterDashboardController::index

recruiter_profile:
    path: /recruteur/mon-profil
    controller: App\Controller\RecruiterProfileController::index

recruiter_new_jobposting:
    path: /recruteur/nouvelle-annonce
    controller: App\Controller\RecruiterNewJobPostingsController::index

recruiter_jobpostings_and_candidates:
    path: /recruteur/annonces-et-candidats/{title}
    controller: App\Controller\RecruiterJobPostingsAndCandidatesController::index