controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

account:
    path: /creer-un-compte
    controller: App\Controller\AccountController::index

